#! /bin/bash
# Este script hace ping a todas las maquinas
# de una sala
# Autor: Jose Pena
# Ult. Fecha de edicion: 12/02/2013
#

read -p "Que sala desea hacerle ping:"
sala=${REPLY:? "no se ha ingresado una sala"}
for sala in [ 1..25 ]
	do
		ping -c 2 $sala
		var=$?
		if [ $var = 0 ] ; Then
			echo " $sala se conecto con exito " >> /holada69
		else
			echo " $sala no se pudo conectar" >> /holada69
		fi	
	done

cat /holada69







